[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "python -m venv /opt/venv --copies",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[phases.start]
cmds = [
  "cd backend && python manage.py migrate",
  "cd backend && python manage.py collectstatic --noinput || true",
  "cd backend && python manage.py runserver 0.0.0.0:8000"
] 