# Generated by Django 5.2.4 on 2025-07-05 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Required. Enter a valid email address.', max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Egyptian phone number (e.g., +201234567890)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Egyptian number.', regex='^\\+201[0-9]{9}$')], verbose_name='Phone Number'),
        ),
    ]
